# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-14 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='remark',
            new_name='name',
        ),
    ]
